# Generated by Django 4.0.5 on 2022-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.TextField(max_length=300)),
                ('joining_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('UttarPradesh', 'UttarPradesh'), ('Gujrat', 'Gujrat')], default='Madhya Pradesh', max_length=30)),
            ],
        ),
    ]
